### PR TITLE
Feature/improve storage behaviour

### PR DESCRIPTION
**Pull request by fabiaant**
Fixes absolutely nothing.
Storage page is a whole lot fancier tho

### CODE REVIEW

**Comment by Jelmerro** [comment]
image
for example

**Comment by Jelmerro** [comment]
which leads to incorrect device types 
image

**Comment by fabiaant** [comment]
Please review again, the issue should be fixed now, but I have not been able to test on Linux yet.

**Comment by Jelmerro** [comment]
image
Looks much better now. Should be good to go.

**Pull request merged**
